### ISSUE TITLE
error after update to new version 

### ISSUE THREAD

**Issue by flatty2804** [MTrab/pyworxcloud#48]
The system cannot restart because the configuration is not valid: Component error: landroid_cloud - Exception importing custom_components.landroid_cloud

now i cannot restart anymore

**Comment by MTrab** [comment]
@r100gs: This error should not be possible, if you are on latest release of landroid_cloud.
Which release are you on?

Same question for you, @flatty2804 - Which release?

**Comment by r100gs** [comment]
I was at 2.1.2 and tried to Go Back to 2.0.3 
--------------------------------

**Comment by MTrab** [comment]
@r100gs that specific error should be fixed in 2.1.3

**Comment by r100gs** [comment]
OK, thx I went to 2.1.3 but I still cannot restart

Component error: landroid_cloud - Exception importing
custom_components.landroid_cloud



Am Do., 30. Juni 2022 um 14:20 Uhr schrieb Malene Trab <
***@***.***>:

**Comment by r100gs** [comment]
ogger: homeassistant.loader
Source: custom_components/landroid_cloud/__init__.py:10
Integration: landroid_cloud (documentation
<https://github.com/MTrab/landroid_cloud/blob/master/README.md>, issues
<https://github.com/MTrab/landroid_cloud/issues>)
First occurred: 14:23:20 (1 occurrences)
Last logged: 14:23:20
Unexpected exception importing component custom_components.landroid_cloud

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 599, in
get_component
    cache[self.domain] = importlib.import_module(self.pkg_path)
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in
import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/config/custom_components/landroid_cloud/__init__.py", line
10, in <module>
    from pyworxcloud import WorxCloud, exceptions
  File "/usr/local/lib/python3.9/site-packages/pyworxcloud/__init__.py",
line 24, in <module>
    from .utils import (
  File "/usr/local/lib/python3.9/site-packages/pyworxcloud/utils/__init__.py",
line 7, in <module>
    from .location import Location
  File "/usr/local/lib/python3.9/site-packages/pyworxcloud/utils/location.py",
line 6, in <module>
    class Location(LDict):
  File "/usr/local/lib/python3.9/site-packages/pyworxcloud/utils/location.py",
line 9, in Location
    def __init__(self, latitude: float | None = None, longitude: float
| None = None):
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'


Am Do., 30. Juni 2022 um 14:25 Uhr schrieb Stefan Söllner <
***@***.***>:

**Comment by MTrab** [comment]
That error cannot come from latest release - that is impossible!
Line 9 as referred to here is line 10 i latest release, and even then, line 10 doesn't look like that!

https://github.com/MTrab/pyworxcloud/blob/d6f7a1e9d82e6afc9b84052934ad77a8337e2956/pyworxcloud/utils/location.py#L10

**Comment by r100gs** [comment]
OK, I try to Reinstall it with Vers. 2.1.3
--------------------------------

**Comment by flatty2804** [comment]
After Update to 2.1.2
Now i cannot restart 



Von meinem iPhone gesendet

**Comment by MTrab** [comment]
Then update to 2.1.3 - if the issue is the same as r100gs describes, then this should be fixed in 2.1.3

**Comment by r100gs** [comment]
Now its working again!

I had im my configuration.yaml the lines
`landroid_cloud:
  - email: !secret  mower_mail
  -password: !secret  mower_pass`

I removed those lines made a restart and everything works again!

THX for all your great help!

**Comment by MTrab** [comment]
So after you removed the YAML config it worked?
That's strange.
Must admit I haven't tested running on a YAML config, as that part of the code haven't been touched.
I'll test that scenario as soon as possible thou.

**Comment by r100gs** [comment]
Yes, In my configuration.yaml I removed the lines. I removed the configured
integration and the landroid_cloud via hacs.
Then restart
After this I addes Version 2.0.3 of your integration again and configured
the integration via ui again.


Am Fr., 1. Juli 2022 um 09:03 Uhr schrieb Malene Trab <
***@***.***>:

**Comment by MTrab** [comment]
I cannot recreate this, not even with YAML config, so I'll close this for now.

if @flatty2804 still has this issue, please create a proper issue with more info on versions and the log entries as well.

**Comment by r100gs** [comment]
Hello,

I tried to reinstall it again. Still no restart possible.

THX for your effort so far!

Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: homeassistant.loader
Source: custom_components/landroid_cloud/__init__.py:10
Integration: Landroid Cloud (documentation, issues)
First occurred: 14:23:20 (3 occurrences)
Last logged: 14:44:24

Unexpected exception importing component custom_components.landroid_cloud
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 599, in
get_component
    cache[self.domain] = importlib.import_module(self.pkg_path)
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in
import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in
_call_with_frames_removed
  File "/config/custom_components/landroid_cloud/__init__.py", line 10, in
<module>
    from pyworxcloud import WorxCloud, exceptions
  File "/usr/local/lib/python3.9/site-packages/pyworxcloud/__init__.py",
line 24, in <module>
    from .utils import (
  File
"/usr/local/lib/python3.9/site-packages/pyworxcloud/utils/__init__.py",
line 7, in <module>
    from .location import Location
  File
"/usr/local/lib/python3.9/site-packages/pyworxcloud/utils/location.py",
line 6, in <module>
    class Location(LDict):
  File
"/usr/local/lib/python3.9/site-packages/pyworxcloud/utils/location.py",
line 9, in Location
    def __init__(self, latitude: float | None = None, longitude: float |
None = None):
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'

Am Do., 30. Juni 2022 um 14:37 Uhr schrieb Malene Trab <
***@***.***>:
